// <auto-generated />
namespace CatanDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NotRequiredPhotoToCreateAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotRequiredPhotoToCreateAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202412041753078_NotRequiredPhotoToCreateAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
