//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatanDataAccess.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CatanDataAccess.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string button_abort {
            get {
                return ResourceManager.GetString("button_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string button_accept {
            get {
                return ResourceManager.GetString("button_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string button_close {
            get {
                return ResourceManager.GetString("button_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string button_confirm {
            get {
                return ResourceManager.GetString("button_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string button_continue {
            get {
                return ResourceManager.GetString("button_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        public static string button_create_game {
            get {
                return ResourceManager.GetString("button_create_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string button_decline {
            get {
                return ResourceManager.GetString("button_decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string button_delete {
            get {
                return ResourceManager.GetString("button_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string button_exit {
            get {
                return ResourceManager.GetString("button_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string button_help {
            get {
                return ResourceManager.GetString("button_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string button_invite {
            get {
                return ResourceManager.GetString("button_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string button_join_game {
            get {
                return ResourceManager.GetString("button_join_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Room!.
        /// </summary>
        public static string button_join_room {
            get {
                return ResourceManager.GetString("button_join_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string button_log_out {
            get {
                return ResourceManager.GetString("button_log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play as a gest.
        /// </summary>
        public static string button_play_as_gest {
            get {
                return ResourceManager.GetString("button_play_as_gest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string button_ready {
            get {
                return ResourceManager.GetString("button_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string button_resend {
            get {
                return ResourceManager.GetString("button_resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Photo.
        /// </summary>
        public static string button_save_photo {
            get {
                return ResourceManager.GetString("button_save_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string button_scoreboard {
            get {
                return ResourceManager.GetString("button_scoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string button_send {
            get {
                return ResourceManager.GetString("button_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string button_view_profile {
            get {
                return ResourceManager.GetString("button_view_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string check_box_show_password {
            get {
                return ResourceManager.GetString("check_box_show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the player you wish to add as a friend.
        /// </summary>
        public static string dialog_add_new_friend {
            get {
                return ResourceManager.GetString("dialog_add_new_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the password change?.
        /// </summary>
        public static string dialog_cancel_change_password_message {
            get {
                return ResourceManager.GetString("dialog_cancel_change_password_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message with a code has been sent to your email or phone number. Please enter the code to save the changes..
        /// </summary>
        public static string dialog_code_sent_message {
            get {
                return ResourceManager.GetString("dialog_code_sent_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this user from your friends list?.
        /// </summary>
        public static string dialog_confirm_remove_friend_message {
            get {
                return ResourceManager.GetString("dialog_confirm_remove_friend_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to vote to expel the player?.
        /// </summary>
        public static string dialog_confirm_vote_kick_player_message {
            get {
                return ResourceManager.GetString("dialog_confirm_vote_kick_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was lost..
        /// </summary>
        public static string dialog_connection_server_exception {
            get {
                return ResourceManager.GetString("dialog_connection_server_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was lost, please try again later.
        /// </summary>
        public static string dialog_connection_server_exception_message {
            get {
                return ResourceManager.GetString("dialog_connection_server_exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load data..
        /// </summary>
        public static string dialog_database_load_exception {
            get {
                return ResourceManager.GetString("dialog_database_load_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save data.
        /// </summary>
        public static string dialog_database_load_exception_message {
            get {
                return ResourceManager.GetString("dialog_database_load_exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save data.
        /// </summary>
        public static string dialog_database_save_exception {
            get {
                return ResourceManager.GetString("dialog_database_save_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the data, please try again.
        /// </summary>
        public static string dialog_database_save_exception_message {
            get {
                return ResourceManager.GetString("dialog_database_save_exception_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields.
        /// </summary>
        public static string dialog_empty_fields {
            get {
                return ResourceManager.GetString("dialog_empty_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields have been left empty.
        /// </summary>
        public static string dialog_empty_fields_message {
            get {
                return ResourceManager.GetString("dialog_empty_fields_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters.
        /// </summary>
        public static string dialog_exception_service {
            get {
                return ResourceManager.GetString("dialog_exception_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This player has been added to your friends list.
        /// </summary>
        public static string dialog_friend_added_message {
            get {
                return ResourceManager.GetString("dialog_friend_added_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join the room, the maximum number of members has been reached..
        /// </summary>
        public static string dialog_full_game_message {
            get {
                return ResourceManager.GetString("dialog_full_game_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room was not found..
        /// </summary>
        public static string dialog_game_not_found_message {
            get {
                return ResourceManager.GetString("dialog_game_not_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code. Please check that it is entered correctly and try again.
        /// </summary>
        public static string dialog_incorrect_code_message {
            get {
                return ResourceManager.GetString("dialog_incorrect_code_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters have been entered.
        /// </summary>
        public static string dialog_invalid_characters_message {
            get {
                return ResourceManager.GetString("dialog_invalid_characters_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters have been entered, please include only numbers, letters, and the symbols &apos;.&apos;, &apos;-&apos;, and &apos;_&apos;..
        /// </summary>
        public static string dialog_invalid_password_characters {
            get {
                return ResourceManager.GetString("dialog_invalid_password_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters have been entered, please include only numbers and letters.
        /// </summary>
        public static string dialog_invalid_username_characters {
            get {
                return ResourceManager.GetString("dialog_invalid_username_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect username or password has been entered.
        /// </summary>
        public static string dialog_invalid_username_password_message {
            get {
                return ResourceManager.GetString("dialog_invalid_username_password_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend has been successfully invited to the game.
        /// </summary>
        public static string dialog_invitation_message {
            get {
                return ResourceManager.GetString("dialog_invitation_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kick the player?.
        /// </summary>
        public static string dialog_kick_player_message {
            get {
                return ResourceManager.GetString("dialog_kick_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been kicked from the room for reason:.
        /// </summary>
        public static string dialog_kicked_player_message {
            get {
                return ResourceManager.GetString("dialog_kicked_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That name was not found registered as an account, please check it and try again.
        /// </summary>
        public static string dialog_name_not_found_message {
            get {
                return ResourceManager.GetString("dialog_name_not_found_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friend requests have been received yet.
        /// </summary>
        public static string dialog_not_friend_request_message {
            get {
                return ResourceManager.GetString("dialog_not_friend_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password updated successfully.
        /// </summary>
        public static string dialog_password_changed {
            get {
                return ResourceManager.GetString("dialog_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been changed successfully.
        /// </summary>
        public static string dialog_password_changed_message {
            get {
                return ResourceManager.GetString("dialog_password_changed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match.
        /// </summary>
        public static string dialog_password_not_match {
            get {
                return ResourceManager.GetString("dialog_password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been cancelled..
        /// </summary>
        public static string dialog_registration_cancelled_message {
            get {
                return ResourceManager.GetString("dialog_registration_cancelled_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request has been rejected.
        /// </summary>
        public static string dialog_reject_friend_request_message {
            get {
                return ResourceManager.GetString("dialog_reject_friend_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove friend.
        /// </summary>
        public static string dialog_remove_friend {
            get {
                return ResourceManager.GetString("dialog_remove_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resent code.
        /// </summary>
        public static string dialog_resent_code {
            get {
                return ResourceManager.GetString("dialog_resent_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has been resent..
        /// </summary>
        public static string dialog_resent_code_message {
            get {
                return ResourceManager.GetString("dialog_resent_code_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request has been sent successfully.
        /// </summary>
        public static string dialog_send_friend_request_message {
            get {
                return ResourceManager.GetString("dialog_send_friend_request_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player has been successfully kicked.
        /// </summary>
        public static string dialog_succes_kick_player_message {
            get {
                return ResourceManager.GetString("dialog_succes_kick_player_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend has been removed successfully.
        /// </summary>
        public static string dialog_succes_remove_friend_message {
            get {
                return ResourceManager.GetString("dialog_succes_remove_friend_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string dialog_success {
            get {
                return ResourceManager.GetString("dialog_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string dialog_success_save_database {
            get {
                return ResourceManager.GetString("dialog_success_save_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered email.
        /// </summary>
        public static string dialog_unregistered_email {
            get {
                return ResourceManager.GetString("dialog_unregistered_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered is not registered..
        /// </summary>
        public static string dialog_unregistered_email_message {
            get {
                return ResourceManager.GetString("dialog_unregistered_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification code has been sent to your email or phone number. Please confirm your account by entering the access code..
        /// </summary>
        public static string dialog_verification_account_message {
            get {
                return ResourceManager.GetString("dialog_verification_account_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, User!.
        /// </summary>
        public static string dialog_welcome {
            get {
                return ResourceManager.GetString("dialog_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been kicked out of the game..
        /// </summary>
        public static string dialog_you_have_been_kicked_message {
            get {
                return ResourceManager.GetString("dialog_you_have_been_kicked_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to my game in Catan!.
        /// </summary>
        public static string email_subject_invite_friends_game {
            get {
                return ResourceManager.GetString("email_subject_invite_friends_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string global_add_friend {
            get {
                return ResourceManager.GetString("global_add_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel change.
        /// </summary>
        public static string global_cancel_change {
            get {
                return ResourceManager.GetString("global_cancel_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Game.
        /// </summary>
        public static string global_create_new_game {
            get {
                return ResourceManager.GetString("global_create_new_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or Phone Number.
        /// </summary>
        public static string global_email_phone_number {
            get {
                return ResourceManager.GetString("global_email_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Request.
        /// </summary>
        public static string global_friend_request {
            get {
                return ResourceManager.GetString("global_friend_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string global_friends {
            get {
                return ResourceManager.GetString("global_friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick Player.
        /// </summary>
        public static string global_kick_player {
            get {
                return ResourceManager.GetString("global_kick_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string global_log_in {
            get {
                return ResourceManager.GetString("global_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string global_password {
            get {
                return ResourceManager.GetString("global_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string global_ready {
            get {
                return ResourceManager.GetString("global_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string global_register {
            get {
                return ResourceManager.GetString("global_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string global_register_user {
            get {
                return ResourceManager.GetString("global_register_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string global_start_game {
            get {
                return ResourceManager.GetString("global_start_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string global_username {
            get {
                return ResourceManager.GetString("global_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Code.
        /// </summary>
        public static string label_access_code {
            get {
                return ResourceManager.GetString("label_access_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATAN SPACE.
        /// </summary>
        public static string label_catan_spacen {
            get {
                return ResourceManager.GetString("label_catan_spacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string label_chat {
            get {
                return ResourceManager.GetString("label_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string label_confirm_password {
            get {
                return ResourceManager.GetString("label_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string label_connected {
            get {
                return ResourceManager.GetString("label_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already registered..
        /// </summary>
        public static string label_email_already_registered {
            get {
                return ResourceManager.GetString("label_email_already_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the room code to join.
        /// </summary>
        public static string label_enter_lobby_code {
            get {
                return ResourceManager.GetString("label_enter_lobby_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your verification code.
        /// </summary>
        public static string label_enter_verification_code {
            get {
                return ResourceManager.GetString("label_enter_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games won.
        /// </summary>
        public static string label_games_won {
            get {
                return ResourceManager.GetString("label_games_won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been kicked from the room..
        /// </summary>
        public static string label_has_been_kicked {
            get {
                return ResourceManager.GetString("label_has_been_kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid email address..
        /// </summary>
        public static string label_invalid_email_message {
            get {
                return ResourceManager.GetString("label_invalid_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Field.
        /// </summary>
        public static string label_message_field {
            get {
                return ResourceManager.GetString("label_message_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Email.
        /// </summary>
        public static string label_new_email {
            get {
                return ResourceManager.GetString("label_new_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string label_new_password {
            get {
                return ResourceManager.GetString("label_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Phone Number.
        /// </summary>
        public static string label_new_phone_number {
            get {
                return ResourceManager.GetString("label_new_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Username.
        /// </summary>
        public static string label_new_username {
            get {
                return ResourceManager.GetString("label_new_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready.
        /// </summary>
        public static string label_no_ready {
            get {
                return ResourceManager.GetString("label_no_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string label_player {
            get {
                return ResourceManager.GetString("label_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string label_recover_password {
            get {
                return ResourceManager.GetString("label_recover_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string label_seconds {
            get {
                return ResourceManager.GetString("label_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting in.
        /// </summary>
        public static string label_starting {
            get {
                return ResourceManager.GetString("label_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player.
        /// </summary>
        public static string label_the_player {
            get {
                return ResourceManager.GetString("label_the_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points.
        /// </summary>
        public static string label_total_points {
            get {
                return ResourceManager.GetString("label_total_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required ACCOUNT fields.
        /// </summary>
        public static string label_user_required_fields {
            get {
                return ResourceManager.GetString("label_user_required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string label_votes {
            get {
                return ResourceManager.GetString("label_votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for players.
        /// </summary>
        public static string label_waiting_players {
            get {
                return ResourceManager.GetString("label_waiting_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string label_weekly {
            get {
                return ResourceManager.GetString("label_weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string label_world {
            get {
                return ResourceManager.GetString("label_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODE: .
        /// </summary>
        public static string message_code {
            get {
                return ResourceManager.GetString("message_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been expelled from the Game.
        /// </summary>
        public static string message_expel_player {
            get {
                return ResourceManager.GetString("message_expel_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has joined the room!.
        /// </summary>
        public static string Message_join_chat {
            get {
                return ResourceManager.GetString("Message_join_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has joined the room..
        /// </summary>
        public static string message_join_room {
            get {
                return ResourceManager.GetString("message_join_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad behavior.
        /// </summary>
        public static string option_bad_behavior {
            get {
                return ResourceManager.GetString("option_bad_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misuse of the game.
        /// </summary>
        public static string option_misuse_game {
            get {
                return ResourceManager.GetString("option_misuse_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string option_undefined {
            get {
                return ResourceManager.GetString("option_undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICATION CODE CATAN.
        /// </summary>
        public static string subject_verification_code {
            get {
                return ResourceManager.GetString("subject_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string window_edit_profile {
            get {
                return ResourceManager.GetString("window_edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick Player.
        /// </summary>
        public static string window_kick {
            get {
                return ResourceManager.GetString("window_kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string window_main_menu {
            get {
                return ResourceManager.GetString("window_main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover account.
        /// </summary>
        public static string window_recover_account {
            get {
                return ResourceManager.GetString("window_recover_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string windows_change_password {
            get {
                return ResourceManager.GetString("windows_change_password", resourceCulture);
            }
        }
    }
}
